apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: candidates-srv
  title: Candidates Service
  description: A microservice for managing candidates.
  annotations:
    github.com/project-slug: Staffing-HQ/candidates-srv
    backstage.io/techdocs-ref: dir:.
    gocd.org/pipelines: backstage,backstage-pr,backstage-builder
  tags:
    - fastapi
    - python
    - openapi
spec:
  type: service
  owner: user:default/efalisotamerat
  lifecycle: experimental
  system: system:default/candidates-system
  dependsOn:
    - 'resource:default/candidates-db'
    - 'api:default/employees-srv-api'
    - 'api:default/internships-srv-api'
  providesApis:
    - 'api:default/candidates-srv-api'
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: candidates-srv-api
  title: Candidates Service API
  description: A microservice for managing candidates.
  annotations:
    github.com/project-slug: Staffing-HQ/candidates-srv
spec:
  type: openapi
  lifecycle: experimental
  owner: user:default/efalisotamerat
  dependsOn:
    - component:default/candidates-srv
  system: system:default/candidates-system
  definition:
    $text: ./openapi.yaml
